function obterFrase (){
    var r_text = new Array ();
    
r_text[0]='S01E03 - "Fácil é o caminho da sabedoria, para aqueles não cegos por si mesmos.';
r_text[2]="S01E04 - Um plano é tão bom quanto os que o realizam.";
r_text[3]="S01E05 - A melhor confiança é construída pela experiência.";
r_text[4]="S01E06 - Confie nos seus amigos, e eles terão razão pra confiar em você.";
r_text[5]="S01E07 - Apoie seus amigos, mantendo o coração mais brando do que a cabeça.";
r_text[6]="S01E08 - Heróis são feitos pelas circunstâncias.";
r_text[7]="S01E09 - Ignore seus instintos à seu próprio risco.";
r_text[8]="S01E10 - O mais poderoso é aquele que controla seu próprio poder.";
r_text[9]="S01E11 - O sinuoso caminho para a paz é sempre o mais digno, apesar das muitas voltas que ele dá.";
r_text[10]="S01E12 - Falhar com honra é melhor do que ter sucesso trapaceando.";
r_text[11]="S01E13 - A cobiça e o medo da perda são as raízes que levam até a árvore do mal.";
r_text[12]="S01E14 - Quando cercado pela guerra, escolha um lado.";
r_text[13]="S01E15 - A arrogância diminui a sabedoria.";
r_text[14]="S01E16 - A verdade ilumina a mente, mas nem sempre traz felicidade ao seu coração.";
r_text[15]="S01E17 - O medo é uma doença, a esperança é a única cura.";
r_text[16]="S01E18 - Uma única chance é uma galáxia de esperança.";
r_text[17]="S01E19 - Dura é a estrada que leva até a grandeza.";
r_text[18]="S01E20 - Os custos da guerra nunca podem ser realmente calculados.";
r_text[19]="S01E21 - O compromisso é uma virtude a ser cultivada, não uma fraqueza para ser desprezada.";
r_text[20]="S01E22 - Um segredo compartilhado é a confiança formada.";
r_text[21]="S02E01 - A lição aprendida é uma lição merecida.";
r_text[22]="S02E02 - Excesso de confiança é a forma mais perigosa de descuido.";
r_text[23]="S02E03 - O primeiro passo para corrigir um erro é a paciência.";
r_text[24]="S02E04 - Um verdadeiro coração, nunca deve ser posto em dúvida.";
r_text[25]="S02E05 - Acredite em si mesmo ou ninguém acreditará.";
r_text[26]="S02E06 - Nenhum presente é mais precioso do que a confiança.";
r_text[27]="S02E07 - As vezes, aceitar a ajuda é mais difícil do que oferecê-la.";
r_text[28]="S02E08 - O apego não é compaixão.";
r_text[29]="S02E09 - Por tudo que você ganha, você perde alguma outra coisa.";
r_text[30]="S02E10 - É a busca pela honra que o faz honroso.";
r_text[31]="S02E11 - O fácil nem sempre é simples."
r_text[32]="S02E12 - Se você ignorar o passado, você compromete seu futuro.";
r_text[33]="S02E13 - Não tema o futuro, não chore o passado.";
r_text[34]="S02E14 - Na guerra, a verdade, é a primeira vítima. ";
r_text[35]="S02E15 - Procurar a verdade é fácil. Aceita-la é difícil.";
r_text[36]="S02E16 - Um líder sábio, sabe quando obedecer.";
r_text[37]="S02E17 - Coragem faz heróis, mas a confiança constrói amizades.";
r_text[38]="S02E19 - A mais perigosa besta é a interior. ";
r_text[39]="S02E20 - Quem, meu pai foi importa menos do que a minha memória dele. ";
r_text[40]="S02E21 - A adversidade é o verdadeiro teste da amizade. ";
r_text[41]="S02E22 - A vingança é uma confissão de dor. ";
r_text[42]="S03E01 - Irmãos de lutas são irmãos para a vida.";
r_text[43]="S03E02 - Lutando em uma guerra testa as habilidades de um soldado, defender seu lar testa seu coração.";
r_text[44]="S03E03 - Onde há uma vontade, existe um caminho.";
r_text[45]="S03e04 -A criança roubada é uma esperança perdida.";
r_text[46]="S03E05 - O desafio da esperança é a de superar a corrupção.";
r_text[47]="S03E06 - Aqueles que cumprem uma lei devem obedece-la.";
r_text[48]="S03E07 - O futuro tem muitos caminhos. Escolha sabiamente";
r_text[49]="S03E08 - Uma falha no planejamento é um plano para o fracasso.";
r_text[50]="S03E09 - O amor vem de todas as formas e tamanhos.";
r_text[51]="S03E10 - O medo é um grande motivador.";
r_text[52]="S03E11 - A verdade pode derrubar o fantasma do medo.";
r_text[53]="S03E12 - O mais rápido caminho para a destruição é através da vingança.";
r_text[54]="S03E13 - Não se nasce com o mal, ele é ensinado.";
r_text[55]="S03E14 - O caminho para o mal pode trazer um grande poder, mas não fidelidade.";
r_text[56]="S03E15 - Equilíbrio é encontrada em quem enfrenta a culpa.";
r_text[57]="S03E16 - Aquele que perde a esperança, desiste da vida.";
r_text[58]="S03E17 - Aquele que busca controlar o destino, nunca encontrará a paz.";
r_text[59]="S03E18 - A adaptação é a chave para a sobrevivência.";
r_text[60]="S03E19 - Qualquer coisa que puder dar errado, irá dar errado.";
r_text[61]="S03E20 - Sem a honra, a vitória é vazia.";
r_text[62]="S03E21 - Sem humildade, a coragem é um jogo perigoso.";
r_text[63]="S03E22 - Um Grande aluno é aquele que o professor espera que seja.";
    var i = Math.floor(64*Math.random())
    document.getElementById("frase").innerHTML = "<p>" + r_text[i] + "</p>";
    }

   